import { SoundLibraryItem, SavedPreset } from '../../types/audio';

export const BUILTIN_SOUND_LIBRARY: SoundLibraryItem[] = [
  // Rain & Storm
  {
    id: 'light-rain',
    name: 'Gentle Rainfall',
    category: 'Rain & Storm',
    description: 'Soft, steady drizzle falling across an open courtyard.',
    audioUrl: '/sounds/light-rain.mp3',
    iconName: 'CloudDrizzle',
    accentColor: '#38BDF8',
  },
  {
    id: 'heavy-rain',
    name: 'Heavy Downpour',
    category: 'Rain & Storm',
    description: 'Dense, immersive rainstorm washing over the landscape.',
    audioUrl: '/sounds/heavy-rain.mp3',
    iconName: 'CloudRain',
    accentColor: '#0EA5E9',
  },
  {
    id: 'rain-on-window',
    name: 'Rain on Windowpane',
    category: 'Rain & Storm',
    description: 'Cozy indoor perspective of raindrops tapping against glass.',
    audioUrl: '/sounds/rain-on-window.mp3',
    iconName: 'Home',
    accentColor: '#60A5FA',
  },
  {
    id: 'rain-on-leaves',
    name: 'Rain on Forest Leaves',
    category: 'Rain & Storm',
    description: 'Crisp botanical patter of raindrops across lush foliage.',
    audioUrl: '/sounds/rain-on-leaves.mp3',
    iconName: 'Trees',
    accentColor: '#34D399',
  },
  {
    id: 'rain-on-tent',
    name: 'Rain on Canvas Tent',
    category: 'Rain & Storm',
    description: 'Warm, sheltered resonance of rain drumming on camp canvas.',
    audioUrl: '/sounds/rain-on-tent.mp3',
    iconName: 'Tent',
    accentColor: '#2DD4BF',
  },
  {
    id: 'rain-on-car-roof',
    name: 'Rain on Car Roof',
    category: 'Rain & Storm',
    description: 'Intimate acoustic shelter inside a parked car during a storm.',
    audioUrl: '/sounds/rain-on-car-roof.mp3',
    iconName: 'Car',
    accentColor: '#818CF8',
  },
  {
    id: 'thunder',
    name: 'Distant Thunderstorm',
    category: 'Rain & Storm',
    description: 'Deep, rolling horizon thunder rumbles across the sky.',
    audioUrl: '/sounds/thunder.mp3',
    iconName: 'CloudLightning',
    accentColor: '#A78BFA',
  },

  // Nature
  {
    id: 'campfire',
    name: 'Crackling Campfire',
    category: 'Nature',
    description: 'Warm cedar logs popping and glowing in a quiet clearing.',
    audioUrl: '/sounds/campfire.mp3',
    iconName: 'Flame',
    accentColor: '#FB923C',
  },
  {
    id: 'river',
    name: 'Mountain River Stream',
    category: 'Nature',
    description: 'Clear, flowing creek water babbling over smooth river stones.',
    audioUrl: '/sounds/river.mp3',
    iconName: 'Waves',
    accentColor: '#2DD4BF',
  },
  {
    id: 'waves',
    name: 'Ocean Shore Waves',
    category: 'Nature',
    description: 'Rhythmic coastal surf rolling onto a sandy beach.',
    audioUrl: '/sounds/waves.mp3',
    iconName: 'Sunset',
    accentColor: '#38BDF8',
  },
  {
    id: 'waterfall',
    name: 'Cascading Waterfall',
    category: 'Nature',
    description: 'Lush natural white noise from a misty forest cascade.',
    audioUrl: '/sounds/waterfall.mp3',
    iconName: 'Droplets',
    accentColor: '#22D3EE',
  },
  {
    id: 'wind-in-trees',
    name: 'Wind Through Pines',
    category: 'Nature',
    description: 'Breezy air currents rustling through tall woodland canopies.',
    audioUrl: '/sounds/wind-in-trees.mp3',
    iconName: 'Wind',
    accentColor: '#10B981',
  },
  {
    id: 'wind',
    name: 'Open Meadow Wind',
    category: 'Nature',
    description: 'Smooth sweeping gusts across high mountain plains.',
    audioUrl: '/sounds/wind.mp3',
    iconName: 'Compass',
    accentColor: '#94A3B8',
  },
  {
    id: 'jungle',
    name: 'Tropical Rainforest',
    category: 'Nature',
    description: 'Rich biodiversity and humid canopy atmosphere.',
    audioUrl: '/sounds/jungle.mp3',
    iconName: 'Palmtree',
    accentColor: '#4ADE80',
  },
  {
    id: 'droplets',
    name: 'Cave Water Droplets',
    category: 'Nature',
    description: 'Echoing mineral water drops in a serene underground cavern.',
    audioUrl: '/sounds/droplets.mp3',
    iconName: 'Droplet',
    accentColor: '#67E8F9',
  },
  {
    id: 'walk-in-snow',
    name: 'Footsteps in Fresh Snow',
    category: 'Nature',
    description: 'Crisp, rhythmic crunch of winter boots on powder snow.',
    audioUrl: '/sounds/walk-in-snow.mp3',
    iconName: 'Snowflake',
    accentColor: '#E2E8F0',
  },

  // Animals & Birds
  {
    id: 'birds',
    name: 'Morning Songbirds',
    category: 'Animals & Birds',
    description: 'Lively sparrows and woodland birds singing at daybreak.',
    audioUrl: '/sounds/birds.mp3',
    iconName: 'Bird',
    accentColor: '#F59E0B',
  },
  {
    id: 'crickets',
    name: 'Summer Night Crickets',
    category: 'Animals & Birds',
    description: 'Peaceful evening chorus of field crickets under the stars.',
    audioUrl: '/sounds/crickets.mp3',
    iconName: 'Moon',
    accentColor: '#34D399',
  },
  {
    id: 'owl',
    name: 'Midnight Forest Owl',
    category: 'Animals & Birds',
    description: 'Soft, resonant owl calls echoing across a moonlit woods.',
    audioUrl: '/sounds/owl.mp3',
    iconName: 'Feather',
    accentColor: '#C084FC',
  },
  {
    id: 'seagulls',
    name: 'Harbor Seagulls',
    category: 'Animals & Birds',
    description: 'Distant coastal bird calls drifting on the sea breeze.',
    audioUrl: '/sounds/seagulls.mp3',
    iconName: 'Anchor',
    accentColor: '#60A5FA',
  },
  {
    id: 'whale',
    name: 'Deep Ocean Whale Song',
    category: 'Animals & Birds',
    description: 'Ethereal, meditative humpback calls beneath the waves.',
    audioUrl: '/sounds/whale.mp3',
    iconName: 'Activity',
    accentColor: '#38BDF8',
  },
  {
    id: 'cat-purring',
    name: 'Cozy Cat Purring',
    category: 'Animals & Birds',
    description: 'Low-frequency soothing purr for calm relaxation.',
    audioUrl: '/sounds/cat-purring.mp3',
    iconName: 'Heart',
    accentColor: '#F472B6',
  },
  {
    id: 'frog',
    name: 'Pond Frogs at Dusk',
    category: 'Animals & Birds',
    description: 'Twilight amphibian chorus beside a quiet lily pond.',
    audioUrl: '/sounds/frog.mp3',
    iconName: 'Sparkles',
    accentColor: '#84CC16',
  },
  {
    id: 'wolf',
    name: 'Distant Timber Wolf',
    category: 'Animals & Birds',
    description: 'Haunting northern wilderness calls across a snowy ridge.',
    audioUrl: '/sounds/wolf.mp3',
    iconName: 'Mountain',
    accentColor: '#94A3B8',
  },

  // City & Places
  {
    id: 'cafe',
    name: 'Parisian Coffee Shop',
    category: 'City & Places',
    description: 'Warm espresso bar murmur, ceramic cups, and soft chatter.',
    audioUrl: '/sounds/cafe.mp3',
    iconName: 'Coffee',
    accentColor: '#F59E0B',
  },
  {
    id: 'library',
    name: 'Quiet Study Library',
    category: 'City & Places',
    description: 'Subtle page turns, soft footsteps, and deep academic focus.',
    audioUrl: '/sounds/library.mp3',
    iconName: 'BookOpen',
    accentColor: '#FBBF24',
  },
  {
    id: 'busy-street',
    name: 'City Street Ambience',
    category: 'City & Places',
    description: 'Lively metropolitan sidewalk energy and distant pedestrians.',
    audioUrl: '/sounds/busy-street.mp3',
    iconName: 'Building2',
    accentColor: '#FB7185',
  },
  {
    id: 'traffic',
    name: 'Late Night City Traffic',
    category: 'City & Places',
    description: 'Smooth urban flow of cars passing along a boulevard.',
    audioUrl: '/sounds/traffic.mp3',
    iconName: 'Navigation',
    accentColor: '#F97316',
  },
  {
    id: 'highway',
    name: 'Distant Highway Hum',
    category: 'City & Places',
    description: 'Steady horizon whoosh of midnight interstate travel.',
    audioUrl: '/sounds/highway.mp3',
    iconName: 'Milestone',
    accentColor: '#A855F7',
  },
  {
    id: 'subway-station',
    name: 'Underground Metro Hub',
    category: 'City & Places',
    description: 'Resonant station acoustics and arriving commuter trains.',
    audioUrl: '/sounds/subway-station.mp3',
    iconName: 'Train',
    accentColor: '#38BDF8',
  },
  {
    id: 'night-village',
    name: 'Sleeping Village Night',
    category: 'City & Places',
    description: 'Still countryside evening with faint, peaceful distance.',
    audioUrl: '/sounds/night-village.mp3',
    iconName: 'Moon',
    accentColor: '#818CF8',
  },
  {
    id: 'temple',
    name: 'Zen Sanctuary Temple',
    category: 'City & Places',
    description: 'Tranquil courtyard atmosphere with subtle wind bells.',
    audioUrl: '/sounds/temple.mp3',
    iconName: 'Bell',
    accentColor: '#FBBF24',
  },
  {
    id: 'underwater',
    name: 'Deep Underwater Abyss',
    category: 'City & Places',
    description: 'Submerged hydrophone warmth and muffled oceanic currents.',
    audioUrl: '/sounds/underwater.mp3',
    iconName: 'Waves',
    accentColor: '#06B6D4',
  },

  // Transport
  {
    id: 'inside-a-train',
    name: 'Sleeper Train Cabin',
    category: 'Transport',
    description: 'Rhythmic rail clatter from inside a warm passenger carriage.',
    audioUrl: '/sounds/inside-a-train.mp3',
    iconName: 'Train',
    accentColor: '#F59E0B',
  },
  {
    id: 'airplane',
    name: 'Night Flight Cabin',
    category: 'Transport',
    description: 'Soothing pressurized cabin hum at 35,000 feet.',
    audioUrl: '/sounds/airplane.mp3',
    iconName: 'Plane',
    accentColor: '#60A5FA',
  },
  {
    id: 'sailboat',
    name: 'Wooden Sailboat Deck',
    category: 'Transport',
    description: 'Gentle hull creaks and water lapping against timber.',
    audioUrl: '/sounds/sailboat.mp3',
    iconName: 'Sailboat',
    accentColor: '#2DD4BF',
  },

  // Objects & Focus
  {
    id: 'keyboard',
    name: 'Mechanical Keyboard',
    category: 'Objects & Focus',
    description: 'Tactile, rhythmic keystrokes for productive deep work.',
    audioUrl: '/sounds/keyboard.mp3',
    iconName: 'Keyboard',
    accentColor: '#A78BFA',
  },
  {
    id: 'vinyl-effect',
    name: 'Warm Vinyl Crackle',
    category: 'Objects & Focus',
    description: 'Nostalgic analog turntable dust and warm needle groove.',
    audioUrl: '/sounds/vinyl-effect.mp3',
    iconName: 'Disc',
    accentColor: '#FB923C',
  },
  {
    id: 'singing-bowl',
    name: 'Tibetan Singing Bowl',
    category: 'Objects & Focus',
    description: 'Pure harmonic bronze resonance for mindfulness and rest.',
    audioUrl: '/sounds/singing-bowl.mp3',
    iconName: 'Radio',
    accentColor: '#FBBF24',
  },
  {
    id: 'wind-chimes',
    name: 'Porch Wind Chimes',
    category: 'Objects & Focus',
    description: 'Delicate metallic chimes dancing in an afternoon breeze.',
    audioUrl: '/sounds/wind-chimes.mp3',
    iconName: 'Music',
    accentColor: '#34D399',
  },
  {
    id: 'clock',
    name: 'Grandfather Clock Tick',
    category: 'Objects & Focus',
    description: 'Steady, grounding mechanical pendulum cadence.',
    audioUrl: '/sounds/clock.mp3',
    iconName: 'Clock',
    accentColor: '#94A3B8',
  },
  {
    id: 'typewriter',
    name: 'Vintage Typewriter',
    category: 'Objects & Focus',
    description: 'Classic writer studio key strikes and carriage returns.',
    audioUrl: '/sounds/typewriter.mp3',
    iconName: 'FileText',
    accentColor: '#F43F5E',
  },
];

export const DEFAULT_STARTER_PRESETS: SavedPreset[] = [
  {
    id: 'preset-rainy-cafe',
    name: 'Rainy Parisian Café',
    description: 'Warm coffee shop chatter with raindrops on the windowpane, distant thunder, and vinyl crackle.',
    createdAt: Date.now() - 86400000 * 5,
    masterVolume: 0.85,
    layers: [
      {
        id: 'cafe',
        name: 'Parisian Coffee Shop',
        category: 'City & Places',
        audioUrl: '/sounds/cafe.mp3',
        iconName: 'Coffee',
        volume: 0.48,
        pan: 0,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 16000, q: 0.7 },
        accentColor: '#F59E0B',
      },
      {
        id: 'rain-on-window',
        name: 'Rain on Windowpane',
        category: 'Rain & Storm',
        audioUrl: '/sounds/rain-on-window.mp3',
        iconName: 'Home',
        volume: 0.65,
        pan: -0.15,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 14000, q: 0.7 },
        accentColor: '#60A5FA',
      },
      {
        id: 'thunder',
        name: 'Distant Thunderstorm',
        category: 'Rain & Storm',
        audioUrl: '/sounds/thunder.mp3',
        iconName: 'CloudLightning',
        volume: 0.38,
        pan: 0.2,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 12000, q: 0.7 },
        accentColor: '#A78BFA',
      },
      {
        id: 'vinyl-effect',
        name: 'Warm Vinyl Crackle',
        category: 'Objects & Focus',
        audioUrl: '/sounds/vinyl-effect.mp3',
        iconName: 'Disc',
        volume: 0.28,
        pan: 0,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 11000, q: 0.7 },
        accentColor: '#FB923C',
      },
    ],
  },
  {
    id: 'preset-sparrow-forest',
    name: 'Sparrow Forest Morning',
    description: 'Real morning songbirds layered with a flowing mountain stream and gentle breeze through the pines.',
    createdAt: Date.now() - 86400000 * 4,
    masterVolume: 0.85,
    layers: [
      {
        id: 'birds',
        name: 'Morning Songbirds',
        category: 'Animals & Birds',
        audioUrl: '/sounds/birds.mp3',
        iconName: 'Bird',
        volume: 0.62,
        pan: -0.15,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 18000, q: 0.7 },
        accentColor: '#F59E0B',
      },
      {
        id: 'river',
        name: 'Mountain River Stream',
        category: 'Nature',
        audioUrl: '/sounds/river.mp3',
        iconName: 'Waves',
        volume: 0.52,
        pan: 0.15,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 15000, q: 0.7 },
        accentColor: '#2DD4BF',
      },
      {
        id: 'wind-in-trees',
        name: 'Wind Through Pines',
        category: 'Nature',
        audioUrl: '/sounds/wind-in-trees.mp3',
        iconName: 'Wind',
        volume: 0.42,
        pan: 0,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 14000, q: 0.7 },
        accentColor: '#10B981',
      },
    ],
  },
  {
    id: 'preset-sleeper-train',
    name: 'Midnight Sleeper Train',
    description: 'Rhythmic rail carriage clatter through a heavy rainstorm with a warm ticking clock.',
    createdAt: Date.now() - 86400000 * 3,
    masterVolume: 0.82,
    layers: [
      {
        id: 'inside-a-train',
        name: 'Sleeper Train Cabin',
        category: 'Transport',
        audioUrl: '/sounds/inside-a-train.mp3',
        iconName: 'Train',
        volume: 0.68,
        pan: 0,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 14000, q: 0.7 },
        accentColor: '#F59E0B',
      },
      {
        id: 'heavy-rain',
        name: 'Heavy Downpour',
        category: 'Rain & Storm',
        audioUrl: '/sounds/heavy-rain.mp3',
        iconName: 'CloudRain',
        volume: 0.45,
        pan: -0.1,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 10000, q: 0.7 },
        accentColor: '#0EA5E9',
      },
      {
        id: 'thunder',
        name: 'Distant Thunderstorm',
        category: 'Rain & Storm',
        audioUrl: '/sounds/thunder.mp3',
        iconName: 'CloudLightning',
        volume: 0.35,
        pan: 0.1,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 12000, q: 0.7 },
        accentColor: '#A78BFA',
      },
    ],
  },
  {
    id: 'preset-coastal-campfire',
    name: 'Coastal Campfire Night',
    description: 'Crackling beach campfire beside rolling ocean waves and summer night crickets.',
    createdAt: Date.now() - 86400000 * 2,
    masterVolume: 0.85,
    layers: [
      {
        id: 'campfire',
        name: 'Crackling Campfire',
        category: 'Nature',
        audioUrl: '/sounds/campfire.mp3',
        iconName: 'Flame',
        volume: 0.65,
        pan: 0,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 16000, q: 0.7 },
        accentColor: '#FB923C',
      },
      {
        id: 'waves',
        name: 'Ocean Shore Waves',
        category: 'Nature',
        audioUrl: '/sounds/waves.mp3',
        iconName: 'Sunset',
        volume: 0.55,
        pan: -0.2,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 14000, q: 0.7 },
        accentColor: '#38BDF8',
      },
      {
        id: 'crickets',
        name: 'Summer Night Crickets',
        category: 'Animals & Birds',
        audioUrl: '/sounds/crickets.mp3',
        iconName: 'Moon',
        volume: 0.36,
        pan: 0.2,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 14000, q: 0.7 },
        accentColor: '#34D399',
      },
    ],
  },
  {
    id: 'preset-city-night',
    name: 'Downtown Rain & Traffic',
    description: 'Urban night boulevard traffic paired with gentle rain and distant subway resonance.',
    createdAt: Date.now() - 86400000,
    masterVolume: 0.8,
    layers: [
      {
        id: 'traffic',
        name: 'Late Night City Traffic',
        category: 'City & Places',
        audioUrl: '/sounds/traffic.mp3',
        iconName: 'Navigation',
        volume: 0.56,
        pan: 0,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 14000, q: 0.7 },
        accentColor: '#F97316',
      },
      {
        id: 'light-rain',
        name: 'Gentle Rainfall',
        category: 'Rain & Storm',
        audioUrl: '/sounds/light-rain.mp3',
        iconName: 'CloudDrizzle',
        volume: 0.58,
        pan: -0.1,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 15000, q: 0.7 },
        accentColor: '#38BDF8',
      },
      {
        id: 'subway-station',
        name: 'Underground Metro Hub',
        category: 'City & Places',
        audioUrl: '/sounds/subway-station.mp3',
        iconName: 'Train',
        volume: 0.26,
        pan: 0.15,
        isMuted: false,
        isSoloed: false,
        filter: { type: 'lowpass', frequency: 9000, q: 0.7 },
        accentColor: '#38BDF8',
      },
    ],
  },
];
